# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  rate:
    default: 1
    description: Number of logs per second to generate.
    type: int
  rotate:
    description: Rotate log after x logs.
    type: int
  format:
    default: json
    description: Log format. Must be recognizeable by flog, e.g. apache_common, apache_combined, apache_error, rfc3164, rfc5424, json.
    type: string
